service: jplay

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-west-1

package:
  artifact: build/distributions/jplay.zip

functions:
  currentTime:
    handler: org.whiteware.Handler
    events:
      - http:
          path: ping
          method: get
